services:
  mysql_db:
    image: mysql:8
    container_name: tarea4_local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tarea4
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

volumes:
  db_data: