services:
  mysql_db:
    image: mysql:8
    container_name: mysql_local
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_local
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mi_base_datos
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin_local
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
    - "8080:80"
    volumes:
    - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pg_data:
  pgadmin_data: