FROM mysql:8

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=SelvaViva

VOLUME [ "/var/lib/mysql" ]

COPY creacionTablas.sql /docker-entrypoint-initdb.d/
COPY insertsTablas.sql /docker-entrypoint-initdb.d/

EXPOSE 3306