services:
  mysql_db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql_local
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: escuela
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: